version: "1.0"
services:
  api:
    build:
      context: api
    ports:
      - "5000:5000"
  wizard:
    build: 
      context: wizard
    volumes:
      - ./wizard:/wizard
    ports:
      - "3000:3000"